#!/usr/bin/env bash
# PreToolUse hook: blocks file-editing tools from touching protected files.
#
# Exit codes:
#   0 -> allowed
#   2 -> blocked (stderr message is fed back to Claude)
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
	echo "protect-files: jq is required but not installed; blocking to fail safe." >&2
	exit 2
fi

FILE_PATH=$(jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[[ -z "$FILE_PATH" ]] && exit 0

BASENAME=${FILE_PATH##*/}

block() {
	echo "Blocked: '$FILE_PATH' is protected ($1). Ask the user before changing it." >&2
	exit 2
}

# Order matters: templates are allowed before the generic .env rule.
case "$BASENAME" in
	*.example | *.sample | *.template) ;;
	.env | .env.*) block "environment file" ;;
	package-lock.json) block "lockfile, generated by npm" ;;
esac

case "/$FILE_PATH/" in
	*/.git/*) block "git internals" ;;
	*/.claude/hooks/*) block "safety hook" ;;
	*/.claude/settings.json/ | */.claude/settings.local.json/) block "claude code settings" ;;
	*/.mcp.json/) block "mcp server config" ;;
esac

exit 0
